#!/bin/bash

# Backup the college folder at nine AM to drive exluding videos and with deletions
rclone sync -v --exclude 'Videos/' --log-file ~/.logs/college_drive_sync.log /home/maxim/College/ Drive:/College/
