#!/bin/bash

# Backup the college folder with deletions to Amazon every eight hours
LOGFILE="$HOME/.logs/college_amazon_sync.log" 

rm "$LOGFILE"
""rclone sync -v --log-file "$LOGFILE" /home/maxim/College/ College:
