#!/bin/bash

# Backup the college folder without the videos to Drive every five minutes
rclone copy -v --exclude 'Videos/' --log-file ~/.logs/college_drive_copy.log /home/maxim/College/ Drive:/College/
