#!/bin/bash

# Backup the college folder at nine AM to drive exluding videos and with deletions
LOGFILE="$HOME/.logs/college_drive_sync.log"

rm "$LOGFILE"
rclone sync -v --exclude 'Videos/' --log-file "$LOGFILE" /home/maxim/College/ Drive:/College/
