#!/bin/bash

# Backup the home folder to Amazon with deletions every third day at 10
LOGFILE="$HOME/.logs/home_amazon_sync.log"

rm "$LOGFILE"
rclone sync -v --exclude 'College/' --exclude 'Backups/' --exclude '*cache*/' --exclude 'temp/' --log-file "$LOGFILE" ~/ LaptopHome:
